### ISSUE TITLE
Left-shift doesn't work

### ISSUE THREAD

**Issue by AXDOOMER** [GoodSign2017/mochadoom#4]
In vanilla Doom, if the right shift is set to run, then it also works with the left shift. I tried with your latest code and the player runs when I press the right shift, but not the left shift.

**Comment by GoodSign2017** [comment]
Okay, tried to patch in 80da691, 74265df

**Comment by AXDOOMER** [comment]
Still doesn't work for me. I also noticed that the right CTRL key doesn't work to fire, but the left CTRL key works.

EDIT: I don't see `vanilla_key_behavior` being added to mochadoom.cfg, I added it myself and it still didn't work.

**Comment by GoodSign2017** [comment]
Try to check it in fa98d51

**Comment by AXDOOMER** [comment]
It works. Thanks.
